# Generated by Django 5.0.3 on 2024-06-10 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('str_id', models.CharField(editable=False, max_length=50, null=True)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_modification', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('canonical_name', models.CharField(blank=True, max_length=50)),
                ('short_description', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('blog_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Body',
                'verbose_name_plural': 'Bodies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InstituteRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Institute Role',
                'verbose_name_plural': 'Institute Roles',
            },
        ),
        migrations.CreateModel(
            name='BodyRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('inheritable', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('official_post', models.BooleanField(default=True)),
                ('permanent', models.BooleanField(default=False)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='locations.body')),
            ],
            options={
                'verbose_name': 'Body Role',
                'verbose_name_plural': 'Body Roles',
                'ordering': ('body__name', 'priority'),
            },
        ),
    ]
