# Generated by Django 5.0.6 on 2024-06-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_body_instituterole_bodyrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='eatery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='hostel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
