# Generated by Django 5.0.6 on 2024-06-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_eatery_location_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='hostel',
            field=models.BooleanField(default=False),
        ),
    ]
