# Generated by Django 5.0.6 on 2024-06-13 00:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_hostel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_ping', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('roll_no', models.CharField(blank=True, max_length=30, null=True)),
                ('ldap_id', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=30, null=True)),
                ('department_name', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=200, null=True)),
                ('join_year', models.CharField(blank=True, max_length=5, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=5, null=True)),
                ('hostel', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=30, null=True)),
                ('show_contact_no', models.BooleanField(default=False)),
                ('fcm_id', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('android_version', models.IntegerField(default=0)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'indexes': [models.Index(fields=['active'], name='locations_u_active_a630c5_idx'), models.Index(fields=['ldap_id'], name='locations_u_ldap_id_28074b_idx')],
            },
        ),
    ]
