# Generated by Django 5.0.6 on 2024-06-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_create_location',
            field=models.BooleanField(default=False),
        ),
    ]
