# Generated by Django 5.0.6 on 2024-06-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_userprofile_can_create_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
    ]
