# Generated by Django 5.0.7 on 2024-07-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_location_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='images',
        ),
    ]
