# Generated by Django 5.0.7 on 2024-07-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_remove_location_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='locations/images/'),
        ),
    ]
